# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/rxcompile/UnrealEngine/UnrealEngine
GAMEPROJECTFILE =/media/rxcompile/Data/UnrealEngine/Projects/SS13Remake/SS13Remake.uproject

TARGETS = \
	SS13Remake-Linux-Debug  \
	SS13Remake-Linux-DebugGame  \
	SS13Remake-Linux-Shipping  \
	SS13Remake-Linux-Test  \
	SS13Remake \
	SS13RemakeEditor-Linux-Debug  \
	SS13RemakeEditor-Linux-DebugGame  \
	SS13RemakeEditor-Linux-Shipping  \
	SS13RemakeEditor-Linux-Test  \
	SS13RemakeEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = mono "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool.exe"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping ShaderCompileWorker UnrealPak UnrealLightmass

StandardSet: RequiredTools UnrealFrontend UE4Editor

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UE4Editor-Linux-Debug


SS13Remake-Linux-Debug:
	 $(PROJECTBUILD) SS13Remake Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

SS13Remake-Linux-DebugGame:
	 $(PROJECTBUILD) SS13Remake Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SS13Remake-Linux-Shipping:
	 $(PROJECTBUILD) SS13Remake Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SS13Remake-Linux-Test:
	 $(PROJECTBUILD) SS13Remake Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

SS13Remake:
	 $(PROJECTBUILD) SS13Remake Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

SS13RemakeEditor-Linux-Debug:
	 $(PROJECTBUILD) SS13RemakeEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

SS13RemakeEditor-Linux-DebugGame:
	 $(PROJECTBUILD) SS13RemakeEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SS13RemakeEditor-Linux-Shipping:
	 $(PROJECTBUILD) SS13RemakeEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SS13RemakeEditor-Linux-Test:
	 $(PROJECTBUILD) SS13RemakeEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

SS13RemakeEditor:
	 $(PROJECTBUILD) SS13RemakeEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /property:TargetFrameworkVersion=v4.5 /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -makefile -kdevelopfile -qmakefile -cmakefile -codelitefile -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
